# Generated by Django 6.0.6 on 2026-06-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='École Al-Nour', max_length=150, verbose_name='Nom')),
                ('school_city', models.CharField(default='Dakar, Sénégal', max_length=100, verbose_name='Ville')),
                ('school_year', models.CharField(default='2024/2025', max_length=20, verbose_name='Année scolaire')),
                ('school_director', models.CharField(default='M. Diop Babacar', max_length=150, verbose_name='Directeur')),
                ('school_email', models.EmailField(default='contact@alnour.sn', max_length=254, verbose_name='Email')),
                ('tuition_fee', models.PositiveIntegerField(default=75000, verbose_name='Frais /trimestre (FCFA)')),
                ('nb_trimestres', models.PositiveSmallIntegerField(default=3, verbose_name='Nb trimestres')),
                ('passing_score', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='Note de passage')),
                ('sms_alerts', models.BooleanField(default=True, verbose_name='Alertes SMS')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres établissement',
            },
        ),
    ]
