# Generated by Django 6.0.6 on 2026-06-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier'),
        ),
    ]
