# Generated by Django 6.0.6 on 2026-06-17 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
        ('core', '0004_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('event_type', models.CharField(choices=[('EXAM', 'Examen / Devoir'), ('HOLIDAY', 'Congé / Vacances'), ('MEETING', 'Réunion / Conseil'), ('SPORT', 'Activité sportive'), ('CULTURAL', 'Événement culturel'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin (optionnel)')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.schoolclass', verbose_name='Classe concernée (optionnel)')),
            ],
            options={
                'verbose_name': 'Événement scolaire',
                'verbose_name_plural': 'Événements scolaires',
                'ordering': ['start_date'],
            },
        ),
    ]
