# Generated by Django 6.0.6 on 2026-06-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='nb_trimestres',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Nombre de trimestres'),
        ),
    ]
