# Generated by Django 6.0.6 on 2026-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schoolclass_nb_trimestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lieu de naissance'),
        ),
    ]
