# Generated by Django 6.0.4 on 2026-07-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_birth_date_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
    ]
