from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard_view, name='dashboard'),
    path('switch-role/<str:role>/', views.switch_role_view, name='switch_role'),
    path('panel/<str:panel_name>/', views.load_panel_view, name='load_panel'),
    path('schedule/<int:class_id>/print/', views.print_schedule_view, name='print_schedule'),
    # Actions HTMX
    path('action/add-schedule/', views.add_class_schedule_view, name='add_class_schedule'),
    path('bulletin/<int:student_id>/print/', views.print_bulletin_view, name='print_bulletin'),
    path('action/send-bulletin/<int:student_id>/', views.send_bulletin_parent_view, name='send_bulletin_parent'),
    path('action/add-student/', views.add_student_view, name='add_student'),
    path('action/delete-student/<int:pk>/', views.delete_student_view, name='delete_student'),
    path('action/save-attendance/', views.save_attendance_view, name='save_attendance'),
    path('action/save-grades/', views.save_grades_view, name='save_grades'),
    path('action/send-message/', views.send_message_view, name='send_message'),
    path('action/upload-document/', views.upload_document_view, name='upload_document'),
    path('action/delete-document/<int:pk>/', views.delete_document_view, name='delete_document'),
    path('action/mark-notifs-read/', views.mark_notifications_read_view, name='mark_notifs_read'),
    path('action/save-settings/', views.save_settings_view, name='save_settings'),
    path('action/add-teacher/', views.add_teacher_view, name='add_teacher'),
    path('action/delete-teacher/<int:pk>/', views.delete_teacher_view, name='delete_teacher'),
    path('action/add-staff/', views.add_staff_view, name='add_staff'),
    path('action/delete-staff/<int:pk>/', views.delete_staff_view, name='delete_staff'),
    path('action/send-reminders/', views.send_unpaid_reminders_view, name='send_unpaid_reminders'),
    path('action/record-payment/', views.record_payment_view, name='record_payment'),
    path('action/record-online-payment/', views.record_online_payment_view, name='record_online_payment'),
    path('payment/receipt/<int:payment_id>/', views.print_receipt_view, name='print_receipt'),
    path('export/students/', views.export_students_excel_view, name='export_students_excel'),
    path('export/grades/', views.export_grades_excel_view, name='export_grades_excel'),
    path('action/import-students/', views.import_students_csv_view, name='import_students_csv'),
    path('action/import-grades/', views.import_grades_csv_view, name='import_grades_csv'),
    path('api/dashboard-stats/', views.dashboard_stats_api, name='dashboard_stats_api'),
    path('api/notif-count/', views.get_notif_count_view, name='notif_count'),
    path('api/search/', views.global_search_view, name='global_search'),
    path('action/save-profile/', views.save_profile_view, name='save_profile'),
    path('action/add-class/', views.add_class_view, name='add_class'),
    path('action/add-subject/', views.add_subject_view, name='add_subject'),
    path('action/delete-class/<int:pk>/', views.delete_class_view, name='delete_class'),
    path('action/delete-subject/<int:pk>/', views.delete_subject_view, name='delete_subject'),
    path('action/load-class-subjects/', views.load_class_subjects_view, name='load_class_subjects'),
    path('action/save-class-subjects/', views.save_class_subjects_view, name='save_class_subjects'),
    # Congés enseignants
    path('action/add-leave/', views.add_leave_view, name='add_leave'),
    path('action/review-leave/<int:pk>/<str:action>/', views.review_leave_view, name='review_leave'),
    path('action/delete-leave/<int:pk>/', views.delete_leave_view, name='delete_leave'),
    # Planning annuel
    path('action/add-event/', views.add_event_view, name='add_event'),
    path('action/delete-event/<int:pk>/', views.delete_event_view, name='delete_event'),
    # Actions Édition Classe
    path('action/edit-class-row/<int:pk>/', views.edit_class_row_view, name='edit_class_row'),
    path('action/edit-class/<int:pk>/', views.edit_class_view, name='edit_class'),
    # Profils Utilisateurs
    path('profile/student/<int:pk>/', views.view_student_profile_view, name='view_student_profile'),
    path('profile/teacher/<int:pk>/', views.view_teacher_profile_view, name='view_teacher_profile'),
    path('profile/staff/<int:pk>/', views.view_staff_profile_view, name='view_staff_profile'),
    path('profile/parent/<int:pk>/', views.view_parent_profile_view, name='view_parent_profile'),
    path('action/update-user-avatar/<int:pk>/', views.update_user_avatar_view, name='update_user_avatar'),
    path('action/edit-student/<int:pk>/', views.edit_student_view, name='edit_student'),
    path('action/edit-teacher/<int:pk>/', views.edit_teacher_view, name='edit_teacher'),
    path('action/edit-staff/<int:pk>/', views.edit_staff_view, name='edit_staff'),
    # Promotion de fin d'année
    path('action/load-promotion-students/', views.load_promotion_students_view, name='load_promotion_students'),
    path('action/execute-promotion/', views.execute_promotion_view, name='execute_promotion'),
    path('promotion/<int:class_id>/print/', views.print_promotion_report_view, name='print_promotion_report'),
    path('action/change-password/', views.change_password_view, name='change_password'),
    # Maintenance Base de Données
    path('action/db-reset/', views.db_reset_view, name='db_reset'),
    path('action/db-restore-demo/', views.db_restore_demo_view, name='db_restore_demo'),
    path('action/db-create-backup/', views.db_create_backup_view, name='db_create_backup'),
    path('action/db-list-backups/', views.db_list_backups_view, name='db_list_backups'),
    path('action/db-restore-backup/', views.db_restore_backup_view, name='db_restore_backup'),
    path('action/db-delete-backup/', views.db_delete_backup_view, name='db_delete_backup'),
]
