# Generated by Django 6.0.6 on 2026-06-17 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('term', models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3')], verbose_name='Trimestre')),
                ('due_date', models.DateField(verbose_name='Date limite')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.schoolclass', verbose_name='Classe (Optionnel)')),
            ],
            options={
                'verbose_name': 'Frais de scolarité',
                'verbose_name_plural': 'Frais de scolarité',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant payé')),
                ('status', models.CharField(choices=[('PAID', 'Payé'), ('PARTIAL', 'Partiel'), ('UNPAID', 'Impayé')], default='UNPAID', max_length=15, verbose_name='Statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement Bancaire'), ('CARD', 'Carte Bancaire')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.studentprofile', verbose_name='Élève')),
                ('tuition_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finances.tuitionfee', verbose_name='Frais de scolarité')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
