# Generated by Django 6.0.6 on 2026-06-18 00:56

import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionfee',
            name='school_year',
            field=models.CharField(default=finances.models.get_current_school_year, max_length=20, verbose_name='Année scolaire'),
        ),
    ]
