# Generated by Django 6.0.6 on 2026-07-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_tuitionfee_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='N° de reçu'),
        ),
    ]
