# Generated by Django 6.0.6 on 2026-07-01 03:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_payment_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant versé')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du versement')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement Bancaire'), ('CARD', 'Carte Bancaire')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence / Notes')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-paid_at'],
            },
        ),
    ]
