# Generated by Django 6.0.6 on 2026-06-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('period', models.CharField(choices=[('MATIN', 'Matin (08h-12h)'), ('APRES_MIDI', 'Après-midi (14h-17h)')], default='MATIN', max_length=20, verbose_name='Période')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'Retard')], default='PRESENT', max_length=15, verbose_name='Statut')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('excuse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif / Justification')),
            ],
            options={
                'verbose_name': 'Présence / Absence',
                'verbose_name_plural': 'Présences / Absences',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi')], verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'Trimestre 1'), (2, 'Trimestre 2'), (3, 'Trimestre 3')], verbose_name='Trimestre')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Note')),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=4, verbose_name='Note maximale')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Coefficient')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commentaire/Appréciation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
    ]
