# Generated by Django 6.0.6 on 2026-06-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='accounts.schoolclass', verbose_name='Classes concernées'),
        ),
        migrations.AddField(
            model_name='subject',
            name='coefficient',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Coefficient par défaut'),
        ),
    ]
