# Generated by Django 6.0.6 on 2026-06-17 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subject_options_subject_classes_and_more'),
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('MALADIE', 'Maladie'), ('CONGE', 'Congé annuel'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], default='CONGE', max_length=20, verbose_name='Type de congé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminprofile', verbose_name='Examiné par')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='accounts.teacherprofile', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Congé enseignant',
                'verbose_name_plural': 'Congés enseignants',
                'ordering': ['-created_at'],
            },
        ),
    ]
