# Generated by Django 6.0.6 on 2026-06-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teacherleave'),
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Coefficient')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_configs', to='accounts.schoolclass', verbose_name='Classe')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_configs', to='academics.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Configuration Matière-Classe',
                'verbose_name_plural': 'Configurations Matière-Classe',
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
