# Generated by Django 6.0.6 on 2026-06-18 00:56

import academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_classsubjectconfig'),
        ('core', '0002_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='school_year',
            field=models.CharField(default=academics.models.get_current_school_year, max_length=20, verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.CharField(default=academics.models.get_current_school_year, max_length=20, verbose_name='Année scolaire'),
        ),
    ]
