# Generated by Django 6.0.6 on 2026-06-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_attendance_school_year_grade_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='devoir_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='N° de devoir'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition')], default='COMPOSITION', max_length=15, verbose_name="Type d'évaluation"),
        ),
    ]
