# Generated by Django 6.0.6 on 2026-06-18 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_grade_devoir_num_grade_grade_type'),
        ('accounts', '0003_schoolclass_nb_trimestres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teacherprofile', verbose_name='Enseignant'),
        ),
    ]
