# Generated by Django 6.0.6 on 2026-07-01 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_grade_teacher_nullable'),
        ('accounts', '0003_schoolclass_nb_trimestres'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='count_in_bulletin',
            field=models.BooleanField(default=True, help_text='Si décoché, ce devoir ne sera pas pris en compte dans la moyenne du bulletin.', verbose_name='Compte dans le bulletin'),
        ),
        migrations.CreateModel(
            name='YearEndReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20, verbose_name='Année scolaire')),
                ('final_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Moyenne annuelle')),
                ('status', models.CharField(choices=[('PASSANT', 'Passant — Passage en classe supérieure'), ('REDOUBLANT', 'Redoublant — Maintien dans la même classe'), ('SORTI', "Sorti — Quitte l'établissement")], default='PASSANT', max_length=15, verbose_name='Décision')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_targets', to='accounts.schoolclass', verbose_name='Classe suivante (si passant)')),
                ('original_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year_end_originals', to='accounts.schoolclass', verbose_name="Classe d'origine")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_end_reports', to='accounts.studentprofile', verbose_name='Élève')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.adminprofile', verbose_name='Validé par')),
            ],
            options={
                'verbose_name': "Bilan de fin d'année",
                'verbose_name_plural': "Bilans de fin d'année",
                'ordering': ['-created_at'],
                'unique_together': {('student', 'school_year')},
            },
        ),
    ]
