# Generated by Django 6.0.6 on 2026-07-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_grade_count_in_bulletin_yearendreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='justification_file',
            field=models.FileField(blank=True, null=True, upload_to='justifications/', verbose_name='Pièce jointe justificative'),
        ),
    ]
